### ISSUE TITLE
How to display the initial value in the form fields?

### ISSUE THREAD

**Issue by olliholliday** [nkalinov/ng2-datetime#11]
I notice that the demo's form fields are blank despite the backing models each having a date set. 

Is there any way to change this so that they display their initial values?

Thanks a lot by the way, it's just what I need.

**Comment by nkalinov** [comment]
@olliholliday Thanks, I'll take a look hopefully today

**Comment by nkalinov** [comment]
Fixed in https://github.com/nkalinov/ng2-datetime/commit/dd9881c958c5e87e8f2d924562eb641e5429c8fa
Version bumped to 1.1.0

**Comment by olliholliday** [comment]
Thanks a lot for the fix, all great now :+1:
