### ISSUE TITLE
Error in binding property

### ISSUE THREAD

**Issue by dantavo** [nkalinov/ng2-datetime#112]
Hi, when i try to use this line of code:
<datetime [(ngModel)]="dateTo" [timepicker]="false" [datepicker]="datepickerToOpts"></datetime>
I get always this error:
 Cannot read property 'icon' of undefined TypeError: Cannot read property 'icon' of undefined...
If I use a basic instance: 
<datetime [(ngModel)]="dateTo" [timepicker]="false"></datetime>
everything work well

**Comment by nkalinov** [comment]
`datepickerToOpts` is undefined
