### ISSUE TITLE
timepicker can't get second value

### ISSUE THREAD

**Issue by guyeyuntian** [nkalinov/ng2-datetime#116]
I set "showSeconds: true" and bind ngModel,but when i refresh the page,timepicker don't show second like this 01:12, but i want 01:12:23. When i click timepicker and set a time, but i can't get the second i set.

**Comment by martinmanzo** [comment]
Hi @guyeyuntian , I had the same problem and fixed it.

I made a fix and opened a pull request that's waiting for approval (https://github.com/nkalinov/ng2-datetime/pull/115).

Let's hope @nkalinov can merge it soon.
