### ISSUE TITLE
Disable the Datepicker completely 

### ISSUE THREAD

**Issue by AngularTx** [nkalinov/ng2-datetime#118]
Is there any option where we can disable the datepicker completely so that the user is not able to click on the date selector icon and make any changes to the data ?

Basically no change in date is allowed .

**Comment by nkalinov** [comment]
`<datetime [readonly]="true" [timepicker]="false"....></datetime>`

**Comment by AngularTx** [comment]
I have added this , but the user is still able to click the date picker
icon and the date selection pop-up is available .




On Feb 15, 2017 1:18 PM, "Nikola Kalinov" <notifications@github.com> wrote:

Closed #118 <https://github.com/nkalinov/ng2-datetime/issues/118>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nkalinov/ng2-datetime/issues/118#event-962640241>, or mute
the thread

**Comment by nkalinov** [comment]
@AngularTx could you retry with 1.4.0. 
I can't seem to reproduce the issue with:
`<datetime [readonly]="true" [timepicker]="false"....></datetime>`

**Comment by Fellach** [comment]
Hi @nkalinov 

I've got the same issue. I can set `[readonly]` only on init the picker. Below you can find what I mean.


- It works - dropdown doesn't appear.
```html
<datetime [readonly]="true" [timepicker]="false"....></datetime>
```

- It works - dropdown appears.
```html
<datetime [readonly]="false" [timepicker]="false"....></datetime>
```

- **Doesn't work - dropdown appears.**
```js
// in component.ts
this.show = false;
// later in the code
setTimeout(() => this.show = true);
```
```html
<datetime [readonly]="show" [timepicker]="false"....></datetime>
```

**Comment by achebrol** [comment]
i think we need to implement setDisabledState( isDisabled : boolean ) : void {} of ControlValueAccessor to make it seamlessly work with Reactive Forms
