### ISSUE TITLE
Destroy method not found

### ISSUE THREAD

**Issue by shoudaos** [nkalinov/ng2-datetime#13]
ngOnDestroy() {
        if (this.datepicker) {
            this.datepicker.destroy(); // destroy method is not found
        }
    }

when switching pages

**Comment by sanathpathiraja** [comment]
getting error on browser.
`EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in ./Attendance class Attendance - inline template:26:18
ORIGINAL EXCEPTION: TypeError: this.datepicker.destroy is not a function
ORIGINAL STACKTRACE:
TypeError: this.datepicker.destroy is not a function`

**Comment by ciesielskico** [comment]
+1,

```
ORIGINAL EXCEPTION: TypeError: this.datepicker.destroy is not a function
ORIGINAL STACKTRACE:
TypeError: this.datepicker.destroy is not a function
    at NKDatetime.ngOnDestroy (http://localhost:4200/vendor/ng2-datetime/src/ng2-datetime//ng2-datetime.js:31:29)
```

**Comment by nkalinov** [comment]
Closed in PR https://github.com/nkalinov/ng2-datetime/pull/14

**Comment by sanathpathiraja** [comment]
I updated  "ng2-datetime": "^1.1.1"
after now it's working
thanks
