### ISSUE TITLE
Increase the width of the control

### ISSUE THREAD

**Issue by AngularLover** [nkalinov/ng2-datetime#131]
How can I make the the width of the datetime field align to my other input fields with class col-sm-9?

Please have a look the at the code!
[MyHtml.txt](https://github.com/nkalinov/ng2-datetime/files/830426/MyHtml.txt)

Thanks

**Comment by subhani1249** [comment]
.input-group {
    float: left;
    width: 49%!important;
    margin-right: 5px;
}
    .input-group input {
        background-color: red !important;
    }

**Comment by cwienands1** [comment]
@subhani1249: Unfortunately, your proposed solution does not work. 
- It shrinks all input-groups on the page to 49%, not just the datetime component. 
- The datetime component is only half the size it is supposed to be.

When I change the 49% value to 99% the group as a whole fills their col-sm-9 container but the button element is three times as wide (i.e. it stretched).

Does anybody have any idea how to make datetime follow the col-... settings.
