### ISSUE TITLE
Using ng2-datetime with SystemJS

### ISSUE THREAD

**Issue by st0rm1x** [nkalinov/ng2-datetime#134]
As title said, I tried to use ng2-datetime with SystemJS and it seems no success.
I have tried to map it accordingly in systemjs.config.js. Several tries and it throws me different kind of errors like 404 Not Found and 403 Forbidden. Anyone having luck integrating with SystemJS please share your configuration. Thanks !

**Comment by lixiayang** [comment]
/*these worked for us...  also needed to import { NKDatetimeModule } from 'ng2-datetime/ng2-datetime'; in app.module and add to imports...  Good luck!*/

(function (global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            app: 'app',
            // angular bundles
            ......
            'ng2-datetime': 'node_modules/ng2-datetime',
			......
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            ......
            'ng2-datetime': {
                defaultExtension: 'js'
            },
            ......
        }
    });
})(this);
