### ISSUE TITLE
Open Datepicker/Timepicker from controller

### ISSUE THREAD

**Issue by Slavrix** [nkalinov/ng2-datetime#137]
Is there currently a way to open the calendar and time picking drop downs from code rather than from clicking the input ?
Id like to have one start opened and the input focussed but cant seem to find a way to do it.

**Comment by nkalinov** [comment]
It should be possible by 
1. Obtain a ref to the component with the [@ViewChild() decorator](https://angular.io/docs/ts/latest/cookbook/component-communication.html).
2. Call `ref.showTimepicker()` and `ref.showDatepicker()`
