### ISSUE TITLE
normalize.css

### ISSUE THREAD

**Issue by vkhLeslie** [nkalinov/ng2-datetime#141]
Module parse failed: F:\hopetaxiapp\fontend\busWap\node_modules\.3.3.7@bootstrap\dist\css\bootstrap.css Unexpected token (7:5) You may need an appropriate loader to handle this file type. | */ | /*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */ | html { | font-family: sans-serif; | -webkit-text-size-adjust: 100%;

**Comment by nkalinov** [comment]
Webpack related
