### ISSUE TITLE
Timepicker doesn't take into account the settings

### ISSUE THREAD

**Issue by ventouris** [nkalinov/ng2-datetime#147]
My html:

```
<datetime [timepicker]="timepickerOpts" [datepicker]="datepickerOpts" [(ngModel)]="applicationContestStatus.deadline" name="workedFrom_docs_date" id="datetimepicker2i_workedFrom_docs_date"></datetime>
```

My composer:

```
  datepickerOpts = {
    format: 'dd/mm/yyyy'
  }

  timepickerOpts = {
    template: 'modal',
    showMeridian: 'false'
  }
```

My module:

```
import 'ng2-datetime/src/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js';
import 'ng2-datetime/src/vendor/bootstrap-timepicker/bootstrap-timepicker.min.js';
import { NKDatetimeModule } from 'ng2-datetime/ng2-datetime';
```

And NKDatetimeModule mentioned on imports.

Datetime works like a charm, but whatever I put on the timepickerOpts, it doesn't work. Also, the timepicker doesn't have the popup to choose a time. And the Meridian are true. If I click on the time icon, it just change both date and time to the current one. 

Version: 1.2.2

**Comment by nkalinov** [comment]
This plugin currently supports only the default timepicker display (dropdown).
