### ISSUE TITLE
Change width of input

### ISSUE THREAD

**Issue by cgebe** [nkalinov/ng2-datetime#149]
```
.input-group {
    width: 100% !important;
} 
```
does not work.

How do you set the width of the input?

**Comment by cgebe** [comment]
Still no solution. Can the width of the input changed at all? If its not possible i have to drop this module.

**Comment by cwienands1** [comment]
How did you solve the problem? I'm facing the same thing.

**Comment by cgebe** [comment]
First i added the `.input-group` class in the css file i directly load into to the component inside the `@Component` annotation. When i moved the code to my theme.css which i load in `styles.less` the class and width change was applied to the calendar. However, using [ViewEncapsulation](https://angular.io/docs/ts/latest/api/core/index/ViewEncapsulation-enum.html) this can also be achieved.
