### ISSUE TITLE
No way to determine empty value after user's interaction?

### ISSUE THREAD

**Issue by argasek** [nkalinov/ng2-datetime#15]
Hi,

When using ng2-datetime (since 1.0.3, now 1.1.0) I encountered the following issue: there is no way (or, at least, I'm unable to find it) to determine that user has deliberately put an empty value. In other words, I'd like to have both date and time fields optional. Currently (1.1.0), assuming the following scenario:
- model variable is initialized with `new Date()`
- user empties the date and time fields, as (s)he doesn't won't to have any value set
- although the text inputs get emptied, the change is not reflected in the model.

At first, I was thinking about using `(blur)` and updating the model myself, yet I realized the event won't get triggered, as we deal with two inputs here. Having `null` / `undefined` if both fields were emptied would be great. (This leads to a separate issue, i.e. how to deal with mixed cases (let's say, only time is provided)).

Is there a way to achieve the required effect?

**Comment by neelsbr** [comment]
Same issue for me. How to achieve required field effect in template driven forms?

**Comment by nkalinov** [comment]
closed / c7d8682df4837e578249df0c9f32f66c17ac28ba
Version bumped to 1.1.4
