### ISSUE TITLE
i18n how to configure

### ISSUE THREAD

**Issue by homx** [nkalinov/ng2-datetime#150]
hi
@nkalinov 
I hope to achieve the Chinese format date, so I think i18n, but did not see how the allocation, please advise.

**Comment by dorthrithil** [comment]
1. Load the language files after loading the datpicker and timepicker scripts. E.g. for the datepicker use `"node_modules/bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min.js",`
2. Pass the desired language to the datetime picker with the date- and timepicker configuration objects. E.g. for the datepicker this could look something like this: `<datetime [(ngModel)]="user.birthday" [timepicker]="false" name="birthday" id="birthday"
 [datepicker]="{language:'zh-CN'}"></datetime>`
