### ISSUE TITLE
does not work in *ngIf directory

### ISSUE THREAD

**Issue by Sluchik** [nkalinov/ng2-datetime#156]

**Comment by wartab** [comment]
It does. Can you be more explicit?

**Comment by Sluchik** [comment]
For exemple.  
<div *ngIf="isOppen">
<div>
     <datetime [(ngModel)]="updateProject.startDate" [timepicker]="false" [datepicker]="datepickerOpts"></datetime>
</div>
</div>

Steps.
1. IsOppen = false - div  with datapiker  is not displeyed
2. isOppen = true-  div  with data pikker displayed but plaggin is not working

**Comment by nkalinov** [comment]
Sorry @Sluchik but I am not able to reproduce this issue...
