### ISSUE TITLE
No updates on options changed

### ISSUE THREAD

**Issue by diegoRodriguezAguila** [nkalinov/ng2-datetime#16]
First, nice lib, there are still very few ng2 libs, so it helped me a lot.
The problem I'm facing is when I want, for example, to change startDate on date picker options it doesn't get updated, I even tried to force the update calling `ngAfterViewInit();` with the new options, but it doesn't get updated. I wanted to know if there is a way to achieve this. 

I'm needing such functionality because I have 2 datepickers, where the first one isn't allowed to have dates after the second one (using the endDate option), and the second one isn't allowed to have dates before the first one (using the startDate option). I think it's a pretty common use case.

PS: when i set the options i.e. `{startDate: new Date()}` when the component is being built, they do work, the problem is when the options are changed.

**Comment by nkalinov** [comment]
You can try to rebuild the component.
i.e.
`<datetime *ngIf="canShow" [(ngModel)]="date" [datepicker]="{startDate: theStartDate}"></datetime>`
then in your component:
````
yourFunction() {
......
    this.canShow = false;
    this.theStartDate = new Date() // or whatever you like
    setTimeout(() => {
        this.canShow = true;
    }, 0);
......
}
````

I'll think of a proper way to change the options.
Thanks!
