### ISSUE TITLE
Not working in Angular Material 2 tabs

### ISSUE THREAD

**Issue by dangviettuan** [nkalinov/ng2-datetime#164]
Datetime picker not working when using inside an Angular 2 Material tab

**Comment by dangviettuan** [comment]
![image](https://cloud.githubusercontent.com/assets/11323132/26568780/6ba4d2b4-4530-11e7-87a4-9f91461d92c8.png)

**Comment by htrex** [comment]
For me it wasn't working in a modal and the ugly workaround to make it work is something like the following:

HTML:
      ....
    <div *ngIf="showDatePicker">
       <datepicker ...>
    </div>
      ....

COMPONENT:
      ....
        modal.open();
        setTimeout( () => {
            this.showDatePicker = true;
        }, 100);
      ....

**Comment by nileshyadav326** [comment]
@htrex  thanks it works for me also.

if possible can you let us know how u have identified the same issue?

**Comment by htrex** [comment]
@nileshyadav326 seems the bug is triggered when the datepicker component is initialized when not visible, so I workarounded it that way.

**Comment by dangviettuan** [comment]
I fixed it by using ViewChild for input tag instead of working with JQuery and tag id. In ng2-datetime datetime is initial by JQuery with tag id so I can use ng2-datetime in component which is hidden by default
