### ISSUE TITLE
Not working with angular cli

### ISSUE THREAD

**Issue by sergeu90** [nkalinov/ng2-datetime#165]
I am using angular cli version   "angular/cli": "^1.0.4", and  i am getting errors 
![image](https://cloud.githubusercontent.com/assets/7217517/26359002/f3df50ea-3fdc-11e7-9890-6edd389916ef.png)

**Comment by wartab** [comment]
Run: `npm install --save @types/jquery`

**Comment by sathish331977** [comment]
After executing "npm install --save-dev @types/jquery" i get the same error

ERROR in C:/APP/node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime
.ts (175,27): Cannot find name 'jQuery'.


ERROR in C:/APP/node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime
.ts (176,37): Cannot find name '$'.


ERROR in C:/APP/docmagic/node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime
.ts (192,19): Cannot find name '$'.


ERROR in C:/APP/docmagic/node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime
.ts (196,27): Cannot find name 'jQuery'.


ERROR in C:/APP/docmagic/node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime
.ts (197,37): Cannot find name '$'.


ERROR in C:/APP/docmagic/node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime
.ts (224,19): Cannot find name '$'.


ERROR in C:/APP/docmagic/node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime
.ts (175,27): Cannot find name 'jQuery'.


ERROR in C:/APP/docmagic/node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime
.ts (176,37): Cannot find name '$'.


ERROR in C:/APP/docmagic/node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime
.ts (192,19): Cannot find name '$'.


ERROR in C:/APP/docmagic/node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime
.ts (196,27): Cannot find name 'jQuery'.


ERROR in C:/APP/docmagic/node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime
.ts (197,37): Cannot find name '$'.


ERROR in C:/APP/docmagic/node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime
.ts (224,19): Cannot find name '$'.

**Comment by MSD007** [comment]
any feedback on this issue yet

**Comment by wartab** [comment]
https://github.com/nkalinov/ng2-datetime/issues/161

**Comment by sathish331977** [comment]
Thanks wartab it worked.

**Comment by sergeu90** [comment]
I have decided the problem added to  "types": ["jquery","mcustomscrollbar"] in the tsconfig.app

**Comment by miguellop1992** [comment]
if you use angular-cli, add in typings.d.ts this:
declare var $: any;
declare var jQuery: any;

**Comment by minhlong** [comment]
Thanks @miguellop1992. it worked.
i have remove in dev and add your script into typings.d.ts

`npm remove --save @types/jquery `

`
declare var $: any;
declare var jQuery: any;
`

**Comment by RobertRajcool** [comment]
@wartab  thanks its works
