### ISSUE TITLE
datetime-Component's HTML code acts more as a form than as a form-input

### ISSUE THREAD

**Issue by wartab** [nkalinov/ng2-datetime#166]
Disclaimer: This is my opinion, you might not agree. I'm open to discussions.

Seeing the HTML template code of this component, I noticed that the whole component is encapsulated in a `div` with the class `form-inline`. Further, both the date and timepickers are encapsulated in a `div` with the following classes: `form-group` and `input-group`. 

Now to my point: this component should not act as a form, but as an input, since it is usually part of a larger form. I forgot to upgrade the version of this package, and did not notice this commit: https://github.com/nkalinov/ng2-datetime/commit/2f180b649aa4a07c532e28ba080cb43467f480b4

This commit added the class `form-group` to the div around the components, which lead to people using this component within a larger form to be completely out of place.

This made a form of mine go from this
![](https://i.gyazo.com/208dd5d43633198994ff88605968bcef.png)

To this:
![](https://i.gyazo.com/20f3ba12d8b669c1f5b7fc236c313eb0.png)

Now my proposition is to (at least optionally) remove all styling attributes that should not to allow for mor flexibility. The user's of this component should be able to decide how to encapsulate the component and not let the component do it on its own. 

This would even allow forms as mine to look like this without hacking Bootstrap's CSS.
![](https://i.gyazo.com/538727339cc494276ccc68cadfc1056b.png)

The solution I propose is therefore: remove the classes `form-inline` and `form-group` inside of the component or make them optional.

**Comment by wrummler** [comment]
My team encountered this issue today. The problem is that `form-group` and `input-group` are used on the same element (commit 2f180b6). Bootstrap's docs specifically [warn](https://getbootstrap.com/css/#callout-formgroup-inputgroup) against this. We work around it in our consuming component by injecting `ElementRef` and removing `form-group` from the native element's child div's `classList`:

```js
this.elementRef.nativeElement.querySelector('div.input-group.form-group').classList.remove('form-group')
```

**Comment by wartab** [comment]
If no one provides a pull request for this, I will do it in around a week when I have time. I didn't know Bootstrap did recommend not doing that, but since they do, it should not even be optional, it should just plain be removed.

**Comment by wartab** [comment]
As stated, I created a pull request to address this issue.
