### ISSUE TITLE
date control never gets touched

### ISSUE THREAD

**Issue by olegsolovey** [nkalinov/ng2-datetime#167]
Subj, although time control does. Anybody knows how to fix that?

**Comment by wartab** [comment]
What is date control? What do you call touched?

**Comment by olegsolovey** [comment]
Date control is a date part of datetime component.

      <div class="row">
        <div class="col-sm-6">
          <div class="form-group form-group-default input-group required"
               [ngClass]="{'has-error': offerForm.get('txtDate').errors && offerForm.get('txtDate').touched }">
            <datetime class="form-control"
                      [datepicker]="datepickerOpts"
                      fromControlName="txtDate"
                      [timepicker]="false">
            </datetime>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="form-group form-group-default input-group input-group bootstrap-timepicker timepicker required"
               [ngClass]="{'has-error': offerForm.get('txtTime').errors && offerForm.get('txtTime').touched }">
            <datetime class="form-control"
                      [datepicker]="false"
                      formControlName="txtTime"
                      [timepicker]="{hideIcon: true}">
            </datetime>
          </div>
        </div>
      </div>

**Comment by olegsolovey** [comment]
misspelling in formControlName (was fromControlName). Closed.
