### ISSUE TITLE
Template change

### ISSUE THREAD

**Issue by zeljko-bulatovic** [nkalinov/ng2-datetime#17]
How to change template? At the moment, date and time inputs are aligned vertically. How can i align them horizontally?

**Comment by nkalinov** [comment]
No way currently to control this from the options.
Have you tried to put the component in a small wrapping div?
I.e.
````
<div style="width: 300px;">
    <datetime *ngIf="canShow" [(ngModel)]="date" [datepicker]="{startDate: theStartDate}"></datetime>
</div>
````
Thanks @zeljko-bulatovic
