### ISSUE TITLE
 The calendar is not taking the styles

### ISSUE THREAD

**Issue by danieloquendo** [nkalinov/ng2-datetime#174]
![image](https://user-images.githubusercontent.com/12579110/28043020-941d8116-6595-11e7-81e2-6ee678dad55d.png)

Windows 10
Node v6.9.1
webpack

**I'm importing these dependencies into my module.ts**

import 'bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js';
import 'bootstrap-timepicker/js/bootstrap-timepicker.min.js';
import { NKDatetimeModule } from 'ng2-datetime/ng2-datetime';

@NgModule({
  imports: [
    NKDatetimeModule
  ]
})

Any idea what could be the issue here?
Thank you.

**Comment by stan-radu-andrei** [comment]
i have the same problem

**Comment by wartab** [comment]
You are very likely not including the CSS files of date and timepicker.

**Comment by stan-radu-andrei** [comment]
yeah. I managed to fix it last night
