### ISSUE TITLE
Destroy is not a function issue

### ISSUE THREAD

**Issue by zeljko-bulatovic** [nkalinov/ng2-datetime#18]
Hello,

I updated ng2-datetime to version 1.1.1, but after i run ng build, copied js file from src/ng2-datetime/ng2-datetime.js still has the old code in the ngOnDestroy() method. 

Should .js file be updated also?

**Comment by davidbonachera** [comment]
Same problem, i'm using the datetime picker inside a modal.

**Comment by nkalinov** [comment]
Fixed in https://github.com/nkalinov/ng2-datetime/commit/ff9921570d200b8d54c40b283a6e1f1b2677a13c
Update to 1.1.2

**Comment by davidbonachera** [comment]
Weird bug, now the annotation isn't found by loading it like this:

 import { NKDatetime } from 'ng2-datetime/ng2-datetime'.

I'm using angular RC1, maybe there is a new way in the RC3 to use directives (since you upgraded the dependcies).
