### ISSUE TITLE
hide disable dates

### ISSUE THREAD

**Issue by sam17896** [nkalinov/ng2-datetime#208]
i want to hide all the dates after 2005 
i have added startDate and endDate attributes but still the picker is showing all the dates.

![image](https://user-images.githubusercontent.com/24951758/32775962-cfe07412-c952-11e7-8809-be5cdbf2a2c1.png)

My picker.html

`<div class="form-group col-md-6">
              <datetime (ngModelChange)="dateChange($event)" [datepicker]="options" [timepicker]="false" [(ngModel)]="dob" name="dob"></datetime>
              <span *ngIf="dateError" style="color:red">{{dateErrorMsg}}</span>
            </div>`

options:
`this.options ={
        startDate: new Date(1920, 1, 1),
        endDate: new Date(2005,1,1),
        orientation:'bottom',
        placeholder:'Date of Birth'
    }`

**Comment by nkalinov** [comment]
The `endDate` attribute will only disable them - https://bootstrap-datepicker.readthedocs.io/en/latest/options.html#enddate
Hiding is not natively supported.
