### ISSUE TITLE
Error: Error: XHR error (404 Not Found) loading+ jQuery

### ISSUE THREAD

**Issue by neelsbr** [nkalinov/ng2-datetime#21]
Hi 

I have followed the install instructions. I have included datepicker like below in ts file

```
import 'ng2-datetime/src/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js';
import 'ng2-datetime/src/vendor/bootstrap-timepicker/bootstrap-timepicker.min.js';
import {NKDatetime} from 'ng2-datetime/ng2-datetime';
```

In system.config.js file
```
map['ng2-datetime'] = 'node_modules/ng2-datetime';
packages['ng2-datetime'] = {defaultExtension: 'js'};
```

In ts file mentioned date like this 
`Purchasedate: any = new Date();`

And used in html like this
`<datetime [(ngModel)]="Purchasedate"></datetime>`

I have included jquery in my index.html file. When i ran the app , I am getting error
(index):34 Error: Error: XHR error (404 Not Found) loading http://localhost:3000/jquery(…)

can you please help me on this?

**Comment by ciesielskico** [comment]
Obviously you need to do the same import steps with jQuery as you did with the bootstrap-date/timepickers.
