### ISSUE TITLE
Breaking Point

### ISSUE THREAD

**Issue by Darth-Vader-2020** [nkalinov/ng2-datetime#210]
The directions are obviously not clear. Most components are a simple download and go. After following the directions, this simply does not work with the latest version of the Angular CLI. I suppose some take pleasure in trying to clean this up, but I am simply not one of those people. I have no choice but to look for another option, or simply develop my own. Given, the eight hours I've wasted trying to get this to work, I should have embarked upon that path a while ago. Nevertheless, as a last ditch effort, I'm going to pose the question: What is the precise configuration required to make this work. I have the following:

**App Module:**
import { NKDatetimeModule } from 'ng2-datetime/ng2-datetime'

@NgModule({
  declarations: [
    AppComponent,
    TimeoffComponent
  ],
  imports: [
    NKDatetimeModule
  ],
  providers: [TscoreService],
  bootstrap: [AppComponent]
})

**ts.appconfig.json**

{
    "extends": "../tsconfig.json",
    "compilerOptions": {
      "outDir": "../out-tsc/app",
      "module": "es2015",
      "baseUrl": "./",
      "types":  [
          "jquery"
      ]
    },
    "exclude": [
      "test.ts",
      "**/*.spec.ts"
    ]
  }

**angular.cli.json**

{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "mobile"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "styles.css",
        "../node_modules/bootstrap/dist/css/bootstrap.css",
        "../node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css",
        "../node_modules/bootstrap-timepicker/css/bootstrap-timepicker.min.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js",
        "../node_modules/bootstrap-timepicker/js/bootstrap-timepicker.js"
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "src/tsconfig.spec.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "e2e/tsconfig.e2e.json",
      "exclude": "**/node_modules/**"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}

Again, this is something that I've been able to do in web applications time and time again. I don't imagine that getting this right can be that complicated. Any help you can provide in getting your stuff to work, would allow me to consider it as a serious solution within our implementation.

**Comment by wartab** [comment]
"does not work" is not really a meaningful problem description. What error messages are you getting? Are these at runtime or during compilation? If no error message, what is the incorrect behavior you are observing?

**Comment by nkalinov** [comment]
Check this issue: https://github.com/nkalinov/ng2-datetime/issues/48
