### ISSUE TITLE
No Directive annotation found on NKDatetime

### ISSUE THREAD

**Issue by alaa-bourouissi** [nkalinov/ng2-datetime#22]
after installing ng2-datetime with npm install --save ng2-datetime

import {NKDatetime} from 'ng2-datetime/ng2-datetime' 

and adding the NKDatetime proprty to the directives of the component ,

The Browser crashes and show this error  : EXCEPTION: Error: Uncaught (in promise): No Directive annotation found on NKDatetime

I'm using this dashboard : https://github.com/akveo/ng2-admin

**Comment by nkalinov** [comment]
https://www.google.bg/search?q=No+Directive+annotation+found+on&oq=No+Directive+annotation+found+on

**Comment by oscarpr** [comment]
some fix?

**Comment by luozt** [comment]
`EXCEPTION: Error: Uncaught (in promise): No Directive annotation found on NKDatetime`
Same problem. @nkalinov Could you help to find the solution? I had checked the above google link which  did not offer me a content answer.
