### ISSUE TITLE
Demo does not load (https://nkalinov.github.io/ng2-datetime/)

### ISSUE THREAD

**Issue by ciesielskico** [nkalinov/ng2-datetime#23]
Error in console: 

GET https://nkalinov.github.io/ng2-datetime/node_modules/@angular/platform-browser//bundles/platform-browser.umd.js 404 (Not Found)

I can see a double slash in the URLafter `/platform-browser//`

**Comment by nkalinov** [comment]
Fixed.
Version bumped to 1.1.3
