### ISSUE TITLE
Will it work with NgForm from angular/forms?

### ISSUE THREAD

**Issue by chsakell** [nkalinov/ng2-datetime#24]
It seems that it doesn't yet. While I have updated my form to use _NgForm_ from _angular/forms_ instead of _NgForm_ from _angular/common_, the datetime directive crashes and reports 
```
**ORIGINAL EXCEPTION**: _No provider for NgControl!_
```
The reason is that since I used angular/forms I removed the reference to **FORM_DIRECTIVES** from _angular/common_.
 Are you going to migrate or support angular/forms?

Thanks

**Comment by nkalinov** [comment]
Thanks @chsakell .
Indeed I haven't tested with @angular/forms but I'm going to do it soon.

**Comment by rafalkasa** [comment]
Hi @nkalinov 

I changed in my local node_modules import ControlValueAccessor, NgControl from @angular/common to @angular/forms and it's working, but I'm waiting for version 1.1.4 with full support in the box for @angular/forms.

Thank you

**Comment by chsakell** [comment]
Hi @nkalinov , 
Any progress on this issue?

**Comment by rafalkasa** [comment]
Hi @chsakell

Please look into created by me pull request. I prepared version that is working with current @angular/forms 0.2.0.

If @nkalinov will accepted my changes this will be available in next ng2-datetime release.

**Comment by ciesielskico** [comment]
+1, having the same issue with new forms module

**Comment by nkalinov** [comment]
closed / c7d8682df4837e578249df0c9f32f66c17ac28ba
