### ISSUE TITLE
UNMET PEER DEPENDENCY @angular/compiler@2.0.0-rc.4

### ISSUE THREAD

**Issue by alaa-bourouissi** [nkalinov/ng2-datetime#25]
When installing ng2-datetime i got this error : 

├── UNMET PEER DEPENDENCY @angular/compiler@2.0.0-rc.4
├── UNMET PEER DEPENDENCY @angular/core@2.0.0-rc.4
├── UNMET PEER DEPENDENCY @angular/platform-browser@2.0.0-rc.4
└─┬ ng2-datetime@1.1.3 
  └── systemjs@0.19.27 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN enoent ENOENT: no such file or directory, open '/home/alaa/WebstormProjects/ng2-admin/node_modules/Ionicons/package.json'
npm WARN @angular/upgrade@2.0.0-rc.3 requires a peer of @angular/compiler@2.0.0-rc.3 but none was installed.
npm WARN @angular/upgrade@2.0.0-rc.3 requires a peer of @angular/core@2.0.0-rc.3 but none was installed.
npm WARN @angular/upgrade@2.0.0-rc.3 requires a peer of @angular/platform-browser@2.0.0-rc.3 but none was installed.

**Comment by nkalinov** [comment]
@alaa-bourouissi That's not coming from the ng2-datetime package. There is only typings as a peer dependency. Check again your package.json
