### ISSUE TITLE
Can not set default value

### ISSUE THREAD

**Issue by ducna1504** [nkalinov/ng2-datetime#27]
H nkalinov,

I'm a new guy with angularjs2 and have some questions about this plugin.

+ How to set default value for date / time picker?
+ How to change (reset) the value manually via a typescript? I tried to set the model object to null but it seems not reflect to UI - even the model is changed.

Please help to check. Thanks!

**Comment by nkalinov** [comment]
Hi @ducna1504, see the [demo](https://nkalinov.github.io/ng2-datetime/) and [sources](https://github.com/nkalinov/ng2-datetime/tree/master/demo).
Resetting the UI (reflecting a null/undefined value) is currently in development.

**Comment by neelsbr** [comment]
Hi @nkalinov 

I have tried as per demo example like `date2= new Date(2015, 3, 2);`. In IE11 & Edge browser it's not setting default date which I mentioned. But chrome is fine. Can you please check this.
