### ISSUE TITLE
can not set default value in IE & Edge

### ISSUE THREAD

**Issue by neelsbr** [nkalinov/ng2-datetime#28]
Hi @nkalinov

I have tried as per demo example like` date2= new Date(2015, 3, 2);` . In IE11 & Edge browser it's not setting default date which I mentioned. But chrome is fine. Can you please check this.

**Comment by rafalkasa** [comment]
Hi @neelsbr 

Problem with initial date is related to the version that you already use. For me in version 1.1.3 problem with set default version is permament in all browses. I created pull request fixing this issue. I'm waiting for version 1.1.4 and right now, I'm using in my project custom version of ng2-datetime component.

Best Regards 
Rafal

**Comment by neelsbr** [comment]
Hi @rafalkasa 

Thanks for your response. I am using 1.1.2 version. Let me wait for 1.1.4 release. Do you have any idea to set mandatory the date field in angular 2 template driven forms?

**Comment by nkalinov** [comment]
Hi guys, @rafalkasa @neelsbr v.1.1.3 Is working fine on my side with an initial date. 
Edge and IE v.11.420

**Comment by rafalkasa** [comment]
Hi @nkalinov 

Hmm, if initial date is working fine for you that can be something related to the language and regional  settings on our machines. I'm using Windows7 and Polish regional settings. I suppose but maybe this is the reason.

I created pull request because of that. JavaScript is running on the client side we should remember that.

**Comment by neelsbr** [comment]
Hi @nkalinov 
It's not working for me as well in the latest version. I am using windows 10. After @rafalkasa fix. It works for me as well

**Comment by rafalkasa** [comment]
Hi @neelsbr

In reference to your question about how to set ng2-datetime field mandatory I don't have good answer for that. I was added required directive in my case but is not working as it should eg.:

<datetime [(ngModel)]="date" name="mydate" #mydate="ngModel" required></datetime>

I have plan to investigate what ja the reason or create issue to the project.

**Comment by nkalinov** [comment]
closed / c7d8682df4837e578249df0c9f32f66c17ac28ba
