### ISSUE TITLE
cant disable the date input text box

### ISSUE THREAD

**Issue by neelsbr** [nkalinov/ng2-datetime#29]
Hi @nkalinov 

I have used following options in datepickerOpts value.
` this.datepickerOpts = {
             autoclose: true,
             todayBtn: 'linked',
             todayHighlight: true,
             format: 'mm/dd/yyyy',
             endDate : new Date(),
             enableOnReadonly : true
           };`

Date picker input text box was still enabled.

**Comment by nkalinov** [comment]
Hi @neelsbr.
Can you describe a bit more your problem ?
`enableOnReadonly`'s default state is `true` [see docs](http://bootstrap-datepicker.readthedocs.io/en/latest/options.html#enableonreadonly)
If you meant that if it's `false`, it's not working as expected - yes, currently this is not supported.

**Comment by neelsbr** [comment]
enableOnReadonly : 
If false the datepicker will not show on a readonly datepicker field.

I have taken above description from the docs. My problem was , I have set the value as true and expectation would be datepicker input box disabled. Can you please let me know this feature was supported ?

**Comment by nkalinov** [comment]
Let me paraphrase this for you:

`enableOnReadonly` - do you want the datepicker to be **enabled** when the input has the `readonly` attribute.
- `true` is the default state: the datepicker will still show on click even if you have the readonly attr. **This does NOT "disable" the input.**
- `false` would mean that the datepicker won't show on `<input readonly />`

Either case, **currently you can't control the readonly attribute** of the datepicker input, but I'll fix this in the 1.1.5 version.

Thanks

**Comment by neelsbr** [comment]
Thanks, @nkalinov . As you said,I want to control the text box readonly attribute

**Comment by neelsbr** [comment]
Hi @nkalinov 

I have tried the below options , self.datepickerOpts = {
       autoclose: true,
       todayBtn: 'linked',
       todayHighlight: true,
       format: 'mm/dd/yyyy',
       endDate : new Date(),
	   enableOnReadonly: true
     };
Looks like date picker not disabled. Can you please check?
