### ISSUE TITLE
Publish RC1 updates on NPM

### ISSUE THREAD

**Issue by jhuntoo** [nkalinov/ng2-datetime#3]
Are the latest updates for RC1 in a publishable state??

**Comment by MinChanSike** [comment]
Cannot find name '$'.
Cannot find name 'jQuery'.
How to import jquery form node.js module?

**Comment by nkalinov** [comment]
@jhuntoo done

**Comment by jhuntoo** [comment]
Thanks!

**Comment by lrezmeri082015** [comment]
I'm using the ng2-datetime v.1.1.4 and I have the same errors: cannot find $, jQuery
