### ISSUE TITLE
$ not found

### ISSUE THREAD

**Issue by paulleyten** [nkalinov/ng2-datetime#32]
Yesterday everything worked ok, after a reboot this night, when running npm start, Typescript cant find JQuery anymore...?

```
node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime.ts(140,37): error TS2304: Cannot find name '$'.
node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime.ts(157,19): error TS2304: Cannot find name '$'.
node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime.ts(161,27): error TS2304: Cannot find name 'jQuery'.
node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime.ts(162,37): error TS2304: Cannot find name '$'.
node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime.ts(189,19): error TS2304: Cannot find name '$'.
```

**Comment by nkalinov** [comment]
Hi @paulleyten,
Try to redo `npm install` or
Install jQuery typescript definitions manually: `typings install --global --save dt~jquery`

**Comment by sarbogast** [comment]
I'm getting the same issue right now, I have tried to delete the node_modules directory and rerun npm install. I installed the typescript definitions manually, but I'm still getting the same error when I run `ng serve`

Yet my package.json does contain the following:

    "bootstrap": "^3.3.7",
    "bootstrap-datepicker": "^1.6.4",
    "bootstrap-timepicker": "^0.5.2",
    "jquery": "^3.1.1",
    "ng2-bootstrap": "^1.1.13",
    "ng2-datetime": "^1.2.1",

**Comment by danielptm** [comment]
I am having the same problem too, I did the advice that nkalinov recommended, but still getting the same error.

**Comment by seza443** [comment]
What worked for me: https://github.com/nkalinov/ng2-datetime/issues/161#issuecomment-323682882
