### ISSUE TITLE
date / year display correction while navigate through year

### ISSUE THREAD

**Issue by neelsbr** [nkalinov/ng2-datetime#33]
Hi @nkalinov  
I have selected Year as 2010-2019, but it displays from 2009-2020. 
 The user navigates to a specified date, but no date selected & discards the calendar. When the calendar is opened again, it shows the previously visited Date/Month/Year. Better it shows currently selected date or If its empty then current date display is fine  (This is the suggestion)

**Comment by nkalinov** [comment]
Hi @neelsbr. Sorry, but I don't understand what the issue is. Could you post some example code and explain a bit clearer.
Thanks

**Comment by neelsbr** [comment]
Hi @nkalinov 
I have attached the screen shot for your reference. Please check and let me know
![calendar picker issue1](https://cloud.githubusercontent.com/assets/6481056/17395054/f558d3ca-5a49-11e6-8348-b0a33a6075f9.png)

**Comment by nkalinov** [comment]
That's related to the https://github.com/eternicode/bootstrap-datepicker functionality.
You could post your idea there.
Thanks
