### ISSUE TITLE
NKDateTime Directive --> 404 GET /node_modules/@angular/forms/

### ISSUE THREAD

**Issue by jeePeel** [nkalinov/ng2-datetime#34]
Hello, i cant figure out why i'll get an 404 on this after adding NKDateTime into the directive Array.

Log excerpt:

`[1] 16.08.02 11:10:08 303 GET /node_modules/@angular/forms`
`[1] 16.08.02 11:10:08 304 GET /node_modules/rxjs/observable/ArrayLikeObservable.js`
`[1] 16.08.02 11:10:08 304 GET /node_modules/rxjs/observable/IteratorObservable.js`
`[1] 16.08.02 11:10:08 304 GET /node_modules/rxjs/operator/observeOn.js`
`[1] 16.08.02 11:10:08 304 GET /node_modules/rxjs/scheduler/FutureAction.js`
`[1] 16.08.02 11:10:08 304 GET /node_modules/rxjs/scheduler/QueueScheduler.js`
`[1] 16.08.02 11:10:08 404 GET /node_modules/@angular/forms/`

**Comment by nkalinov** [comment]
Hi @jeePeel, This is not related to the component, but your build setup as you have 404.
Please post your config, (webpack or systemjs or requirejs), whatever you use - I'll try to help you.
