### ISSUE TITLE
Date picker sent wrong UTC time

### ISSUE THREAD

**Issue by neelsbr** [nkalinov/ng2-datetime#35]
Hi @nkalinov 

I am using following code. `<datetime required [(ngModel)]="Purchasedate" [ngModelOptions]="{standalone: true}" [timepicker]="false" [datepicker]="datepickerOpts"></datetime>`

Whenever form submits, I am getting 5.30 hrs delay time . I am in IST time zone. It's assuming time was 12 AM and sending the previous date. Basically, I have opted date option so better avoid UTC time calculation here. Please check and let me know your comments 
For Eg : I have chosen 16 July 2016. But in my form submit always returning as 2016-06-15T18:30:00.000Z

In my case, I am not saving time . So date saved wrongly in the database. Is that possible to get date alone which I choose

**Comment by nkalinov** [comment]
Hi @neelsbr ,
Your `ngModel` contains a "local" date object on date change (IST timezone in your case). 
If you need to show the "good" date to people in other timezones, you should save it in UTC (`.toUTCString()`) in the database.

**Comment by neelsbr** [comment]
Hi @nkalinov 
I have used toUTCstring() method. Its working fine
