### ISSUE TITLE
TypeError: $(...).datepicker is not a function

### ISSUE THREAD

**Issue by Redigast13** [nkalinov/ng2-datetime#40]
Here is my imports:
```
import 'jquery/src/jquery';

import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap/dist/js/bootstrap.min.js';

import 'ng2-datetime/src/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js';
import 'ng2-datetime/src/vendor/bootstrap-timepicker/bootstrap-timepicker.min.js';
```
My component:
```
import { NKDatetime } from 'ng2-datetime/ng2-datetime';
@Component({
   ...
   directives: [NKDatetime],
})

```
Template:
`<datetime [formControl]="date" [ngModel]="dateValue"></datetime>`

I get an error: TypeError: $(...).datepicker is not a function. angular rc-5

**Comment by rohan2934** [comment]
facing the same issue. Can you please tell me how did you resolved?

**Comment by Redigast13** [comment]
> 
facing the same issue. Can you please tell me how did you resolved?
> 
In my case the problem was in webpack configuration.
Adding jquery to externals section in webpack config fixed it:
```
externals: {
    // require("jquery") is external and available
    //  on the global var jQuery
    "jquery": "jQuery"
},
```

**Comment by dinesh36** [comment]
I got the same issue with webpack,
I have following entries for the webpack
```
config.entry = {
		webapp:['./client/main.js'], //application generated code will be here 
		polyfills:['./client/polyfills.browser.js'], //pollyfills will be here
		vendor:['./client/vendor.browser.js'] //external vendor files will be here.
	};
```
My jQuery is been added to **vendor.browser.ts** file. And following code

```
import { NKDatetime } from 'ng2-datetime/ng2-datetime';
@Component({
   ...
   directives: [NKDatetime],
})
```
was in **app.module.ts** file. So It's not able to fetch the jQuery there. 

So I have made following change. 

Set the following code 

```
import { NKDatetime } from 'ng2-datetime/ng2-datetime';
export {NKDatetimeModule} //export the ng2 module from the vendor.ts file.
```

In *vendor.ts* file. 

and  

```
import { NKDatetimeModule } from '../../vendor.browser'; //import the exported ng2-datetime module here.
@Component({
   ...
   directives: [NKDatetime],
})
```

In my **app.module.ts** file.

And It works...

**Comment by cwienands1** [comment]
I solved it the following way:
_Disclaimer, I'm not using vendor.ts and my project started from angular2-webpack-starter, with angular2-webpack-starter-bootstrap  merged in._

In styles.scss:
@import '~bootstrap/dist/css/bootstrap.min.css';
@import '~bootstrap/dist/css/bootstrap-theme.min.css';
@import '~bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css';
@import '~bootstrap-timepicker/css/bootstrap-timepicker.min.css';

In app.module.ts:
...
import '../styles/styles.scss';
import 'jquery/dist/jquery.min.js'
import 'bootstrap/dist/js/bootstrap.js';
import 'bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js';
import 'bootstrap-timepicker/js/bootstrap-timepicker.min.js';
import { NKDatetimeModule } from 'ng2-datetime/ng2-datetime';
...
@NgModule({
  imports: [
...
    NKDatetimeModule,
  ],
...

**Comment by chetanahire00** [comment]
I added the following entries to angular.cli.json and it works.  I am using angular 4.2

"styles": [
	"styles.css",
	"../node_modules/font-awesome/css/font-awesome.css",
	"../node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css"
],
"scripts": [
	"../node_modules/jquery/dist/jquery.min.js",
	"../node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js",
	"../node_modules/bootstrap-timepicker/js/bootstrap-timepicker.js"
]
