### ISSUE TITLE
cant disable the date input text box in 1.1.5

### ISSUE THREAD

**Issue by neelsbr** [nkalinov/ng2-datetime#43]
Hi @nkalinov

I have used following options in datepickerOpts value.
self.datepickerOpts = {
       autoclose: true,
       todayBtn: 'linked',
       todayHighlight: true,
       format: 'mm/dd/yyyy',
       endDate : new Date(),
	   enableOnReadonly: true
     };

Date picker input text box was still enabled. can you please check this?

**Comment by nkalinov** [comment]
@neelsbr:
If you want to make the input readonly, you need to set the `readonly` option to `true` / eg. `<datetime readonly="true" ...></datetime>`
This will also set the enableOnReadonly property to `false`
