### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by danielptm** [nkalinov/ng2-datetime#44]
After spending about 5 hours following the installation isntructions, and variations of configurations, I could not get ng2-datetime to work with rc4. I think improvement of the installation instructions including what versions of angular2, forms, etc are required to use this would make it easier to work with.

**Comment by wartab** [comment]
I recommend you let us know WHAT is not working. What did you do? What are the error messages?
I had no trouble using this package for RC4, so the issue must be on your side.
