### ISSUE TITLE
Webpack + NKDatetime

### ISSUE THREAD

**Issue by niallduggan** [nkalinov/ng2-datetime#45]
Cant get this to work with webpack. can anyone help out?

vendor.ts file has this. 
`import 'ng2-datetime';`

webpack.config.vendor.js  has the following:
`var path = require('path');
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var extractCSS = new ExtractTextPlugin('vendor.css');
var isDevelopment = process.env.ASPNETCORE_ENVIRONMENT === 'Development';

module.exports = {
    resolve: {
        extensions: ['', '.js']
    },
    module: {
        loaders: [
            { test: /\.(png|woff|woff2|eot|ttf|svg)$/, loader: 'url-loader?limit=100000' },
            { test: /\.css/, loader: extractCSS.extract(['css']) }
        ]
    },
    entry: {
        vendor: [
            'bootstrap',
            'bootstrap/dist/css/bootstrap.css',
            'style-loader',
            'jquery',
            '@angular/common',
            '@angular/compiler',
            '@angular/core',
            '@angular/http',
            '@angular/platform-browser',
            '@angular/platform-browser-dynamic',
            '@angular/router',
            'moment',

            'ng2-bootstrap',
            'ng2-datetime',
            'ng2-bs3-modal',
            'alertifyjs'
        ]    
    },       
    output: {
        path: path.join(__dirname, '../wwwroot', 'dist'),
        filename: '[name].js',
        library: '[name]_[hash]',
    },
    plugins: [
        extractCSS,
        new webpack.optimize.OccurenceOrderPlugin(),
        new webpack.DllPlugin({
            path: path.join(__dirname, '../wwwroot', 'dist', '[name]-manifest.json'),
            name: '[name]_[hash]'
        })
    ].concat(isDevelopment ? [] : [
        new webpack.optimize.UglifyJsPlugin({
            compress: { warnings: false },
            minimize: true,
            mangle: false // Due to https://github.com/angular/angular/issues/6678
        })
    ])
};
`

And my app.module.ts has this. 
`import { NKDatetime } from 'ng2-datetime/ng2-datetime';`

No build error and when i run the app with all this commented out it works fine. But i need the datepickers.

This is the error im getting.. 

`Uncaught Error: Unexpected value 'NKDatetime' declared by the module 'AppModule'(anonymous function) @ compiler.umd.js:14166CompileMetadataResolver.getNgModuleMetadata @ compiler.umd.js:14153RuntimeCompiler._compileComponents @ compiler.umd.js:16777RuntimeCompiler._compileModuleAndComponents @ compiler.umd.js:16715RuntimeCompiler.compileModuleAsync @ compiler.umd.js:16706PlatformRef_._bootstrapModuleWithZone @ core.umd.js:9488PlatformRef_.bootstrapModule @ core.umd.js:9470(anonymous function) @ boot-client.ts:19__webpack_require__ @ bootstrap 4cb6055…:19(anonymous function) @ bootstrap 4cb6055…:39__webpack_require__ @ bootstrap 4cb6055…:19(anonymous function) @ bootstrap 4cb6055…:39(anonymous function) @ bootstrap 4cb6055…:39
`

**Comment by chocapic54** [comment]
I thinl you must wait @nkalinov  published the new version related to this MR https://github.com/nkalinov/ng2-datetime/pull/42 on NPM

**Comment by niallduggan** [comment]
Thanks. any idea when this will be!?

**Comment by chocapic54** [comment]
I hope it will be soon because i'm a blocked too

**Comment by DominicSachs** [comment]
Same problem here.

**Comment by mlessio** [comment]
Same here, but just fixed and sent a pull request to @nkalinov here https://github.com/nkalinov/ng2-datetime/pull/50

**Comment by DominicSachs** [comment]
If i use your fork, i see the following error in the console. 
Unexpected value 'NKDatetimeModule' imported by the module ...

webpack version: 1.13.0

**Comment by chocapic54** [comment]
yes, i had it too, you must remove ng2-datetime.d.ts file

**Comment by mlessio** [comment]
It sounds very strange. I am using my fork and it works pretty well. Have you tried removing the ng2-datetime folder from node_modules/ and running npm install?

**Comment by mlessio** [comment]
It seems that the new webpack version has broken the module declaration. Also removing .d.ts is not working for me. 
@chocapic54 which version of webpack are you compiling against?

**Comment by DominicSachs** [comment]
Same problem here. Removing ng2-datetime.d.ts is not working for me.

**Comment by chocapic54** [comment]
strange, because it works for me...
i'm using webpack 1.13.2

**Comment by mlessio** [comment]
@chocapic54 this is strange. i'm using 1.13.2 too. I'll try to fix it now.

**Comment by chocapic54** [comment]
in addition to that, i've updated package.json :
`{
  "name": "ng2-datetime",
  "version": "1.1.5-benny",
  "description": "Boostrap Datetime picker plugin",
  "repository": {
    "url": "http://gitlab.pharmagest.com/diatelic/ng2-datetime.git"
  },
  "main": "ng2-datetime.js",
  "publishConfig": {
    "registry": "http://nexus.diatelic.info/repository/npm-internal/"
  },
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "bootstrap": "3.3.7",
    "bootstrap-datepicker": "1.6.4",
    "bootstrap-timepicker": "0.5.2",
    "core-js": "2.4.1",
    "jquery": "2.2.3",
    "reflect-metadata": "0.1.8",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.27",
    "zone.js": "0.6.23"
  },
  "devDependencies": {
    "concurrently": "2.0.0",
    "jasmine-core": "2.4.1",
    "karma": "0.13.22",
    "karma-es6-shim": "0.2.3",
    "karma-jasmine": "0.3.8",
    "karma-phantomjs-launcher": "1.0.0",
    "lite-server": "2.2.0",
    "phantomjs-polyfill": "0.0.2",
    "phantomjs-prebuilt": "2.1.5",
    "typescript": "2.0.2"
  }
}`

**Comment by mlessio** [comment]
Is the version online(on your fork) up to date with the one you are using successfully?

**Comment by chocapic54** [comment]
no, i don't know how to push it online cause it's configured to be deployed on my own nexus

**Comment by mlessio** [comment]
just go on your repo folder(assuming you cloned it via git) and do:
`
git add .
git commit
git push
`

**Comment by mlessio** [comment]
SOLVED.

It is a problem in the package.json
A quick fix will be to remove the ng2-datetime/node_modules subfolder that is being created due to outdated dependencies. I'll update them ASAP.

**Comment by mlessio** [comment]
@chocapic54 @DominicSachs  Now it seems solved on my fork. Please give it a try. 👍

**Comment by chocapic54** [comment]
i can't push cause it goes to "madweb" server

**Comment by mlessio** [comment]
@chocapic54 now it should go also if you use my fork.

**Comment by chocapic54** [comment]
my local version was already good, i've no problem since yesterday, everything works

**Comment by DominicSachs** [comment]
Great, the problem is solved.

**Comment by mlessio** [comment]
@DominicSachs +1

**Comment by Piusha** [comment]
Hi
I also having same error 
Uncaught Error: Unexpected value 'NKDatetime' imported by the module 'AppModule'"..

Any Idea for this?

**Comment by mlessio** [comment]
Check in your lib folder node_modules/ng2-datetime.
If you have a node_modules subdolder (node_modules/ng2-datetime/node_modules) delete it and rebuild your project(if needed). it should work fine.

**Comment by Piusha** [comment]
Thanks mlessio. It was the issue. I removed and  it worked
