### ISSUE TITLE
Option to hide the input field

### ISSUE THREAD

**Issue by TianCNCA** [nkalinov/ng2-datetime#46]
Hi,

Is it possible to hide the input fields.

Thanks,

**Comment by chocapic54** [comment]
Hi,

Can you detailed your demand please ?

If you want to hide one of input (time for example) you have to do this : 
`<datetime  [datepicker]="{ format: 'dd/mm/yyyy', autoclose: true }" [timepicker]="false">
</datetime>`

**Comment by TianCNCA** [comment]
Hi,

What I meant was hiding the input fields for manually entering the date or time. We want to only display the button on the page. With the original jQuery library all you need to do is not providing a input element, but since you've hard coded that into your template in this angular2 library, we can't opt to hide it from outside.

Hope I've made it clear.

Thanks,

**Comment by nkalinov** [comment]
@TianCNCA Have you tried with CSS ?
