### ISSUE TITLE
Missing jQuery declarations in the node package source code

### ISSUE THREAD

**Issue by TianCNCA** [nkalinov/ng2-datetime#47]
Version is the latest: 1.1.5.

In src/ng2-datetime.ts these two loc's are missing:
```
declare var $: any;
declare var jQuery: any;
```
and VS2015 complains about them. It can be easily fixed by adding them locally but I thought I should let the maintainers of this repo know this.

Thanks,

**Comment by rakibler** [comment]
Does this actually fix everything for you? With a fresh install of ng2-datetime, when I 
```

import 'jquery/dist/jquery.min.js';
import {NKDatetime} from 'ng2-datetime/ng2-datetime';
import 'ng2-datetime/src/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js';
import 'ng2-datetime/src/vendor/bootstrap-timepicker/bootstrap-timepicker.min.js';
```

into my AppModule and then import NKDatetime into my declarations, I get 
`bootstrap-timepicker.min.js:5Uncaught ReferenceError: jQuery is not defined`

**Comment by TianCNCA** [comment]
You need to install the typings of jQuery as well. The missing declarations don't really affect the build as long as you have the typings installed. I just don't like seeing errors.

**Comment by rakibler** [comment]
I did that by doing typings install dt~jquery --global but still get the errors. Am I missing anything?

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Sep 14, 2016 at 5:52 PM -0400, "Tian" <notifications@github.com<mailto:notifications@github.com>> wrote:


You need to install the typings of jQuery as well. The missing declarations don't really affect the build as long as you have the typings installed. I just don't like seeing errors.
