### ISSUE TITLE
datepicker is not a function

### ISSUE THREAD

**Issue by DominicSachs** [nkalinov/ng2-datetime#53]
My Imports:
`import { NKDatetimeModule } from "ng2-datetime/ng2-datetime";

@NgModule({
    imports: [FormsModule, ReactiveFormsModule, CommonModule, NKDatetimeModule],
    declarations: [AppComponent]
})
export class MyModule { }`

My HTML:
`<datetime [timepicker]="false" [formControl]="form.controls['startDate']"></datetime>`

I already tried the solution from [this Issue](https://github.com/nkalinov/ng2-datetime/issues/40). Is there anything to do to make it working?

jQuery: 2.2.3
Angular: 2.0.0 (final)
Webpack: 1.13.0

**Comment by nkalinov** [comment]
Which version are you using ? 1.2.0 should resolve this

**Comment by DominicSachs** [comment]
There was a missing import in my code.
Now i always get the error "No provider for NgControl".

`<form [formGroup]="form" novalidate>
<datetime [timepicker]="false" [(ngModel)]="model.date" formControlName="date"></datetime>
</form>`

**Comment by cwienands1** [comment]
I solved it the following way:
_Disclaimer, I'm not using vendor.ts and my project started from angular2-webpack-starter, with angular2-webpack-starter-bootstrap  merged in._

In styles.scss:
@import '~bootstrap/dist/css/bootstrap.min.css';
@import '~bootstrap/dist/css/bootstrap-theme.min.css';
@import '~bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css';
@import '~bootstrap-timepicker/css/bootstrap-timepicker.min.css';

In app.module.ts:
...
import '../styles/styles.scss';
import 'jquery/dist/jquery.min.js'
import 'bootstrap/dist/js/bootstrap.js';
import 'bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js';
import 'bootstrap-timepicker/js/bootstrap-timepicker.min.js';
import { NKDatetimeModule } from 'ng2-datetime/ng2-datetime';
...
@NgModule({
  imports: [
...
    NKDatetimeModule,
  ],
...

**Comment by drunkendaddy** [comment]
I added the following entries to angular.cli.json and it works.

```
"styles": [
        "styles.css",
        "../node_modules/font-awesome/css/font-awesome.css",
        "../node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js",
        "../node_modules/bootstrap-timepicker/js/bootstrap-timepicker.js"
      ]
```
