### ISSUE TITLE
'datetime' is not a known element

### ISSUE THREAD

**Issue by szykov** [nkalinov/ng2-datetime#56]
> Error: Template parse errors:
> 'datetime' is not a known element:
> 1. If 'datetime' is an Angular component, then verify that it is part of this module.
> 2. If 'datetime' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. (" <div class="input-group date">
>             [ERROR ->]<datetime [(ngModel)]="date"></datetime>
>             <input type="date" class="form-control" id="dat"): 

app.module.ts
```
...
import { NKDatetimeModule } from 'ng2-datetime/ng2-datetime';
...
@NgModule({
  imports: [
    ...
    NKDatetimeModule,
    ...
  ],
  ...
  bootstrap: [AppComponent]
})
export class AppModule { }
```
app.component.html
`<datetime [(ngModel)]="date"></datetime>`

system.config.js
````
(function (global) {
    System.config({
        paths: {
      // paths serve as alias
            'npm:': 'node_modules/'
        },
    // map tells the System loader where to look for things
        map: {
      // our app is within the app folder
            app: 'js/app',
      // angular bundles
     ....
     //other
     'ng2-datetime': "npm:ng2-datetime",
        },
    // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            'ng2-datetime': {
                main: './ng2-datetime.js',
                defaultExtension: 'js'
            },
            app: {
                main: './main.js',
                defaultExtension: 'js'
            },
            rxjs: {
                defaultExtension: 'js'
            }
        }
    });
})(this);
```

Why? Angular2 somehow don't see this component and don't recognize datetime html tag...
I use latest 2.0.1 angular version.

**Comment by Sfairet** [comment]
I have same problem. And use datetime as in [readme](https://github.com/nkalinov/ng2-datetime/blob/master/README.md) example not working, because @Component.directives deprecated in Angular RC6.

**Comment by nkalinov** [comment]
Try to put this in the `declarations` list also:

````
import { NKDatetimeModule } from 'ng2-datetime/ng2-datetime';

@NgModule({
  ...
  declarations: [ NKDatetimeModule ]
  ...
})
````

**Comment by szykov** [comment]
@nkalinov i think a know what was a reason of the failure. I was using multiple modules and forgot to export it in one of them for use in others. I think i will close this issue.

Спасибо :)
