### ISSUE TITLE
Angular 2.0.0 and Bootstrap v4

### ISSUE THREAD

**Issue by BenDevelopment** [nkalinov/ng2-datetime#57]
Hi,
Do you plan to upgrade your datetime picker to Angular 2.0.0 and Bootstrap v4 in a near futur ?

Ben

**Comment by nkalinov** [comment]
Hi,
The component is built for Angular 2.0.0.
Bootstrap4 support depends on the related plugins, I've just made a ng2 wrapper for them, so don't expect that from me.
