### ISSUE TITLE
Datepicker does not unsubscribe

### ISSUE THREAD

**Issue by starostin** [nkalinov/ng2-datetime#59]
Hi. I have faced with one issue. When you override datepicker options in he class, component call init method each time. But before init it does not unsubscribe from previous events.

My solution is:
`this.datepicker.datepicker('destroy'); this.datepicker.off('changeDate');`
`this.timepicker.timepicker('remove'); this.datepicker.off('changeTime')`

Call this in ngOnChanges method;

**Comment by nkalinov** [comment]
Hi, @starostin,
The `ngOnChanges` method calls `this.datepicker.datepicker('destroy');` which in turns detaches the events.
Please describe more your problem.
