### ISSUE TITLE
ng2-datetime not working firefox

### ISSUE THREAD

**Issue by sanathpathiraja** [nkalinov/ng2-datetime#6]
getting error,
EXCEPTION: Error in demo/app.component.html:38:41 platform-browser.umd.js:971
EXCEPTION: Error in demo/app.component.html:38:41 platform-browser.umd.js:962:17

ORIGINAL EXCEPTION: RangeError: date value is not finite in DateTimeFormat.format() platform-browser.umd.js:962:17

ORIGINAL STACKTRACE: platform-browser.umd.js:962:17

DateFormatter</DateFormatter.format@http://localhost:3000/node_modules/@angular/common/common.umd.js:1021:24
DatePipe</DatePipe.prototype.transform@http://localhost:3000/node_modules/@angular/common/common.umd.js:1047:20
pureProxy2/<@http://localhost:3000/node_modules/@angular/core/core.umd.js:8376:26
anonymous/_View_AppComponent0.prototype.detectChangesInternal@AppComponent.template.js:896:64
AppView</AppView.prototype.detectChanges@http://localhost:3000/node_modules/@angular/core/core.umd.js:9996:13
DebugAppView</DebugAppView.prototype.detectChanges@http://localhost:3000/node_modules/@angular/core/core.umd.js:10084:17
AppView</AppView.prototype.detectViewChildrenChanges@http://localhost:3000/node_modules/@angular/core/core.umd.js:10016:17
AppView</AppView.prototype.detectChangesInternal@http://localhost:3000/node_modules/@angular/core/core.umd.js:10007:13
AppView</AppView.prototype.detectChanges@http://localhost:3000/node_modules/@angular/core/core.umd.js:9996:13
DebugAppView</DebugAppView.prototype.detectChanges@http://localhost:3000/node_modules/@angular/core/core.umd.js:10084:17
ViewRef_</ViewRef_.prototype.detectChanges@http://localhost:3000/node_modules/@angular/core/core.umd.js:9397:58
ApplicationRef_</ApplicationRef_.prototype.tick/<@http://localhost:3000/node_modules/@angular/core/core.umd.js:9047:79
ApplicationRef_</ApplicationRef_.prototype.tick@http://localhost:3000/node_modules/@angular/core/core.umd.js:9047:17
ApplicationRef_</ApplicationRef_.prototype._loadComponent@http://localhost:3000/node_modules/@angular/core/core.umd.js:9018:13
ApplicationRef_</ApplicationRef_.prototype.bootstrap/<@http://localhost:3000/node_modules/@angular/core/core.umd.js:9007:17
ApplicationRef_</ApplicationRef_.prototype.run/<@http://localhost:3000/node_modules/@angular/core/core.umd.js:8978:30
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:323:20
NgZoneImpl/this.inner<.onInvoke@http://localhost:3000/node_modules/@angular/core/core.umd.js:6075:36
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:322:20
Zone</Zone</Zone.prototype.run@http://localhost:3000/node_modules/zone.js/dist/zone.js:216:25
NgZoneImpl</NgZoneImpl.prototype.runInner@http://localhost:3000/node_modules/@angular/core/core.umd.js:6106:64
NgZone</NgZone.prototype.run@http://localhost:3000/node_modules/@angular/core/core.umd.js:6330:55
ApplicationRef_</ApplicationRef_.prototype.run@http://localhost:3000/node_modules/@angular/core/core.umd.js:8976:13
ApplicationRef_</ApplicationRef_.prototype.bootstrap@http://localhost:3000/node_modules/@angular/core/core.umd.js:8998:20
coreLoadAndBootstrap/</<@http://localhost:3000/node_modules/@angular/core/core.umd.js:8790:47
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:323:20
NgZoneImpl/this.inner<.onInvoke@http://localhost:3000/node_modules/@angular/core/core.umd.js:6075:36
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:322:20
Zone</Zone</Zone.prototype.run@http://localhost:3000/node_modules/zone.js/dist/zone.js:216:25
scheduleResolveOrReject/<@http://localhost:3000/node_modules/zone.js/dist/zone.js:571:53
Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:356:24
NgZoneImpl/this.inner<.onInvokeTask@http://localhost:3000/node_modules/@angular/core/core.umd.js:6066:36
Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:355:24
Zone</Zone</Zone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:256:29
drainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:474:26
ZoneTask/this.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:426:22

**Comment by nkalinov** [comment]
Hi @sanathpathiraja, I just finished testing and the problem comes from the `date2` property not being able to initialize with `new Date('2016-06-08 10:00:00')` on Firefox. 
Still don't know why, but it is browser related.
Fixed the demo in https://github.com/nkalinov/ng2-datetime/commit/bb799cc4fdedfe6ab5fe534643453c6ebd787f78
Thanks!

**Comment by sanathpathiraja** [comment]
now it's working 
thanks
