### ISSUE TITLE
Can not bind a date

### ISSUE THREAD

**Issue by DominicSachs** [nkalinov/ng2-datetime#60]
I can not bind a date. The input is always empty.

Html
`<datetime name="startDate" id="startDate" [(ngModel)]="model.startDate" formControlName="startDate" [timepicker]="false" [datepicker]="datepickerOpts"></datetime>`

Options:
`    datepickerOpts = {
        autoclose: true,
        todayBtn: 'linked',
        todayHighlight: true,
        assumeNearbyYear: true,
        format: 'dd.mm.yyyy'
    }`

![image](https://cloud.githubusercontent.com/assets/5363927/19230592/ac2f3570-8ed5-11e6-8e03-fcd0039ac6fa.png)

**Comment by DominicSachs** [comment]
I also tried it without angular forms. There is only this code in my HTML template.

```
<div class="form-group">
    <datetime name="startDate" id="startDate" [(ngModel)]="model.startDate" 
              [timepicker]="false" [datepicker]="datepickerOpts"></datetime>
    {{ model.startDate }}
</div>
```

The start date is available but the input is always empty.

![image](https://cloud.githubusercontent.com/assets/5363927/19261816/da1ccd9e-8f93-11e6-9d2d-bfb5ee27415f.png)

**Comment by nkalinov** [comment]
Could you try to
1. remove `format` option
2. use another string for `format`

**Comment by DominicSachs** [comment]
I tried both but without success.

**Comment by DominicSachs** [comment]
It seems the object binding is the problem.

This binding works fine: 
`<datetime [(ngModel)]="dateProperty" name="myDate" [datepicker]="datepickerOpts" [timepicker]=false></datetime>`

This version doesn't work:
`<datetime [(ngModel)]="obj.myDateProperty" name="myDate" [datepicker]="datepickerOpts" [timepicker]=false></datetime>`

**Comment by DominicSachs** [comment]
The date comes from a service. It seems that the view is not refreshed. Timing problem?

this._myService.get(id)
                    .subscribe((data) => {
                       // myObj.startDate is the date to bind
                        this.myObj = data;
                    });

**Comment by Jagadeesh-Govindaraj** [comment]
from https://github.com/zoechi

There is no way to know for TS/JS that this value is a date. It's a string and treated as such. Other data types are distinguishable but JSON doesn't provide any special support for date. You need to convert it manually.

See for example this discussion how to transport and convert a date using JSON [Format a Microsoft JSON date?](http://stackoverflow.com/questions/206384/format-a-microsoft-json-date)


http://stackoverflow.com/questions/36746760/how-to-receive-date-field-from-json-service

http://stackoverflow.com/questions/35917808/how-to-get-date-object-from-json-response-in-typescript

**Comment by vishwa1004** [comment]
set time dropdown not vissible?? <datetime [(ngModel)]="datetime"></datetime>
