### ISSUE TITLE
Localization: Cannot read property 'dates' of undefined

### ISSUE THREAD

**Issue by DominicSachs** [nkalinov/ng2-datetime#66]
I want to use localization. If I import the locale file from bootstrap-datepicker, the following error message occurs. 
"Uncaught TypeError: Cannot read property 'dates' of undefined"

Now I found a solution to get this working. I removed your node_modules folder (with the jquery package) and everything works fine.
Is there any solution for this problem.

These are my imports:

```
import 'ng2-datetime/src/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js';
import 'ng2-datetime/src/vendor/bootstrap-timepicker/bootstrap-timepicker.min.js';
import { NKDatetimeModule } from 'ng2-datetime/ng2-datetime';
import "../../../../node_modules/bootstrap-datepicker/dist/locales/bootstrap-datepicker.de.min.js";
```

**Comment by nitin27may** [comment]
I am getting same issue. Can you please suggest that how we can fix that.
I am using Webapck, Date picker is working fine,
In vendor.ts I have added

`import 'jquery/src/jquery';
import 'ng2-datetime/src/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js';
import 'bootstrap-datepicker/js/locales/bootstrap-datepicker.fr';
import 'ng2-datetime/src/vendor/bootstrap-timepicker/bootstrap-timepicker.min';
import 'bootstrap/dist/js/bootstrap';`

Earlier it was working fine far both french and English, but after updation of package versions to

"bootstrap-datepicker": "1.6.1",
 "bootstrap-timepicker": "^0.5.2",
  "ng2-datetime": "1.3.2",

It is not working as expected for french, getting error
`bootstrap-datepicker.fr.js:6 Uncaught TypeError: Cannot read property 'dates' of undefined
    at bootstrap-datepicker.fr.js:6
    at Object.<anonymous> (bootstrap-datepicker.fr.js:18)
    at Object.<anonymous> (bootstrap-datepicker.fr.js:18)
    at __webpack_require__ (bootstrap 5e45fbe…:686)
    at fn (bootstrap 5e45fbe…:105)
    at Object.<anonymous> (polyfills.ts:24)
    at __webpack_require__ (bootstrap 5e45fbe…:686)
    at fn (bootstrap 5e45fbe…:105)
    at Object.<anonymous> (zone.js:2095)
    at __webpack_require__ (bootstrap 5e45fbe…:686)
    at Object.defineProperty.value (bootstrap 5e45fbe…:781)
    at bootstrap 5e45fbe…:781`

**Comment by SrAxi** [comment]
I'm getting the same error with Angular-cli. When using `ng test` I'm gettinh the following error too:

> Chrome 59.0.3071 (Windows 10 0.0.0) ERROR
>   Uncaught TypeError: Cannot read property 'dates' of undefined
>   at webpack:///~/bootstrap-datepicker/dist/locales/bootstrap-datepicker.de.min.js:1:0 <- src/test.ts:124797
> 
> Chrome 59.0.3071 (Windows 10 0.0.0) ERROR
>   Uncaught TypeError: Cannot read property 'dates' of undefined
>   at webpack:///~/bootstrap-datepicker/dist/locales/bootstrap-datepicker.de.min.js:1:0 <- src/test.ts:124797

It would be great to have a solution for this and not having to fork the project in order to remove the node_modules's jQuery package...
