### ISSUE TITLE
 $(...).datepicker is not a function

### ISSUE THREAD

**Issue by hasher** [nkalinov/ng2-datetime#69]
I get this error when I try to use datetime component. How can I install this in my ng2 application using angular-cli? 

` $(...).datepicker is not a function`

**Comment by jesujcastillom** [comment]
+1

**Comment by jesujcastillom** [comment]
This is because the bootstrap-datepicker.min.js is not loaded yet, ensure you load that before this call is made.

**Comment by nkalinov** [comment]
@hasher see @jesujcastillom's comment.
Ensure that the required dependencies are loaded **before** you use the component.

**Comment by cyberbobjr** [comment]
Hi,
I've the same problem, how can you load the bootstrap-datepicker.min.js with Webpack please ?

Thank for your help,
best regards

**Comment by nkalinov** [comment]
@cyberbobjr 
````
import 'bootstrap/dist/css/bootstrap.css';
import 'jquery/dist/jquery.min.js';
import 'ng2-datetime/src/vendor/bootstrap-datepicker/bootstrap-datepicker3.min.css';
import 'ng2-datetime/src/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js';
import 'ng2-datetime/src/vendor/bootstrap-timepicker/css/bootstrap-timepicker.min.css';
import 'ng2-datetime/src/vendor/bootstrap-timepicker/js/bootstrap-timepicker.js';
````

**Comment by dolfandringa** [comment]
@nkalinov Can you elaborate on how to do that with angular-cli. I have added 

"../node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.js",
"../node_modules/bootstrap-timepicker/js/bootstrap-timepicker.js"   

to my scripts:[] in angular-cli.json. That should be enough right? I am still getting the error though somehow,
