### ISSUE TITLE
Typings is added as a devDependency

### ISSUE THREAD

**Issue by justinmchase** [nkalinov/ng2-datetime#7]
In your `package.json` file you have:
```
 "postinstall": "typings install",
```

But then in your devDependencies:
```
"devDependencies": {
  "typings": "^0.8.1"
}
```

Therefore installing this dependency fails for non-typescript projects. Typings should either be set as a `"dependency"` or a `"peerDependency"`

**Comment by nkalinov** [comment]
Fixed in https://github.com/nkalinov/ng2-datetime/pull/8
Thanks
