### ISSUE TITLE
Trigger function on change

### ISSUE THREAD

**Issue by well-made** [nkalinov/ng2-datetime#72]
I've noticed there is a (dateChange) attribute available for the datetime compontent but it doesn't seem to be triggered.

Is there a way to trigger a function on changing the date?

Thanks :)

**Comment by temitope-akinduro** [comment]
Yes there is just bind to the change event

so it would be: <datetime (change)=""dateChange($event)></datetime>

**Comment by well-made** [comment]
I tried that, but when I do this is the corresponding function I don't get a console log:

`dateChange(event) {
        console.log(event);
    }`

**Comment by well-made** [comment]
Gentle bumb
