### ISSUE TITLE
NKDateTime - unable to integrate in Unit Tests with WebPack

### ISSUE THREAD

**Issue by raghubala** [nkalinov/ng2-datetime#79]
FAILED TESTS:                                                                                                                                                                               
  Create Company                                                                                                                                                                            
    × should have an url                                                                                                                                                                    
      PhantomJS 2.1.1 (Windows 8 0.0.0)                                                                                                                                                     
    Error: Error in ./CreateCompanyPage class CreateCompanyPage - inline template:79:36 caused by: undefined is not a constructor (evaluating '$('#' + this.idDatePicker).datepicker(options
)') in karma-shim.js (line 74311)                                                                                                                                                           
    init@webpack:///~/ng2-datetime/src/ng2-datetime/ng2-datetime.ts:89:0 <- karma-shim.js:53278:68                                                                                          
    ngAfterViewInit@webpack:///~/ng2-datetime/src/ng2-datetime/ng2-datetime.ts:20:0 <- karma-shim.js:53209:18                                                                               
    detectChangesInternal                                                                                                                                                                   
    detectChanges@webpack:///~/@angular/core/src/linker/view.js:219:0 <- karma-shim.js:74189:35                                                                                             
    detectChanges@webpack:///~/@angular/core/src/linker/view.js:324:0 <- karma-shim.js:74294:48

**Comment by nkalinov** [comment]
I guess you don't have properly configured your karma to include all the packages.
