### ISSUE TITLE
Hide timepicker dynamically

### ISSUE THREAD

**Issue by fortunella** [nkalinov/ng2-datetime#80]
I want to hide the timepicker dynamically when the user checks a seperate checkbox (all day checkbox).

How can I do this?

**Comment by nkalinov** [comment]
Please refer to docs.
It is basically setting `[timepicker]="false"`

**Comment by fortunella** [comment]
Yes, that works fine in my template. But what I want to do is, to remove the timepicker dynamically when the user clicks the all day checkbox.

In my component class I defined a @ViewChild variable:

@ViewChild('eventFrom') eventFrom;

When I stop the debugger inside the component, I see that this variable is of type NgModel and that it has a field of type NkDatetime. But I cannot figure out how to let the timepicker disapper.

eventFrom.timepicker = null;
eventFrom.timepicker = false;
eventFrom.valueAccessor.timepicker = null;
eventFrom.valueAccessor.timepicker = false;

All of these do not have any effect on my page. the timepicker is still displayed. What do I have to do, to let it disappear when the user clicks the checkbox?
