### ISSUE TITLE
Could you please make the NgModel to accept Number data type as well ?

### ISSUE THREAD

**Issue by lmq009** [nkalinov/ng2-datetime#82]
Hi,

Thank you so much for building this component.

We are using your datetime component like this:

<datetime name="createdDate" [(ngModel)]="message.createdDate" readonly></datetime>

Because this 'createdDate' field is retrieved from database and passed to the front with JSON format, And JSON doesn't support Date type.  So it is a Number (the milliseconds) field now.

It will save lots of our trouble if you could make NgModel to accept Number.  ( Just like the way the Date Pipe is doing) .

Thanks again.

Mark

**Comment by nkalinov** [comment]
@lmq009 I'm not planning to do this as of now - it is your responsibility to convert the timestamp to Date
