### ISSUE TITLE
Shows cannot find jQuery on gitbash terminal.

### ISSUE THREAD

**Issue by sanathpathiraja** [nkalinov/ng2-datetime#9]
It's working perfectly.
but shows this on githbash terminal.

> [default] ../node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime.ts:95:27
    Cannot find name 'jQuery'.

**Comment by nkalinov** [comment]
@sanathpathiraja You don't have the jQuery typescript definitions.
You can read more about this in [this tutorial](http://blog.mgechev.com/2016/03/28/ambient-type-definitions-duplicate-identifier-typescript-fix/).
"Fixed" in https://github.com/nkalinov/ng2-datetime/pull/8

**Comment by sanathpathiraja** [comment]
I updated to
"typescript": "^1.8.10"
"typings": "^1.0.4"
 
still coming this error,
`[default] ../node_modules/ng2-datetime/src/ng2-datetime/ng2-datetime.ts:95:27
Cannot find name 'jQuery'.`

**Comment by seza443** [comment]
What worked for me: https://github.com/nkalinov/ng2-datetime/issues/161#issuecomment-323682882
