### ISSUE TITLE
Not possible to reset datepicker to empty state using ngModel

### ISSUE THREAD

**Issue by alexlucky21** [nkalinov/ng2-datetime#91]
Hi Nikola,

I believe it is a bug that it's not possible to reset datepicker to empty state using ngModel (setting date as null after it was not null).

I updated your NKDatetime.writeValue() from:
if (isDate(this.date)) {
TO:
if (isDate(this.date) || this.date == null) {

Please fix.

Thanks,
Alex

**Comment by nkalinov** [comment]
hi @alexlucky21 have you tried with v 1.2.2 ?

**Comment by alexlucky21** [comment]
Everything s fine in 1.2.2.

Thanks,
Alex
