### ISSUE TITLE
ng2-datetime 404 (Not Found)

### ISSUE THREAD

**Issue by comeback4u** [nkalinov/ng2-datetime#93]
http://localhost:3000/ng2-datetime/ng2-datetime 404 (Not Found)scheduleTask 
event:44 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/ng2-datetime/ng2-datetime(…)

I don't know whats the problem but i followed below septs and getting this error any solution ?

**Comment by nkalinov** [comment]
@comeback4u how we are supposed to help without info what is not working and what have you tried?
