### ISSUE TITLE
Cannot read property 'extend' of undefined TypeError: Cannot read property 'extend' of undefined     at NKDatetime.init (ng2-datetime.ts:146)     at NKDatetime.ngAfterViewInit (ng2-datetime.ts:67)     at CompiledTemplate.proxyViewClass.View_PreferencesComponent0.detectChangesInternal (component.ngfactory.js:699)

### ISSUE THREAD

**Issue by jaykadam** [nkalinov/ng2-datetime#94]
error_handler.js:53 Error: Uncaught (in promise): Error: Error in ./PreferencesComponent class PreferencesComponent - inline template:25:16 caused by: Cannot read property 'extend' of undefined
TypeError: Cannot read property 'extend' of undefined
    at NKDatetime.init (ng2-datetime.ts:146)
    at NKDatetime.ngAfterViewInit (ng2-datetime.ts:67)
    at CompiledTemplate.proxyViewClass.View_PreferencesComponent0.detectChangesInternal (component.ngfactory.js:699)

**Comment by nkalinov** [comment]
jQuery is undefined, make sure you imported it before trying to use it
