### ISSUE TITLE
On wrong date it selectes todays date

### ISSUE THREAD

**Issue by vsanat** [nkalinov/ng2-datetime#97]
Hi there,

Can you please tell me why it selects today's date if I enter wrong date(a,b,c.. in the input). is it possible to override this feature, can I give my own error message on wrong date entry?

thanks.

**Comment by nkalinov** [comment]
I don't think that's currently possible.
You can, though, [disable the parsing of the input](http://bootstrap-datepicker.readthedocs.io/en/latest/options.html#forceparse) and have your own parser/validator which will update the model.
